const devs = [
    {
        id        : 1,
        name      : 'Md Kayda Azam',
        age       : 18,
        skill     : 'Laravel',
        income    : 1000,
        location  : 'Dhaka',
        gender    : 'male',
        photo     : 'https://www.brandedgirls.com/wp-content/uploads/2015/11/almousa_su-700x.jpeg',
      },
      {
        id        : 2,
        name      : 'Liam',
        age       :  20,
        skill     : 'Django',
        income    : 2000,
        location  : 'Chittagong',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIfejzFMlcp_Hj2X7jCfvzFHMAu5yW0plj3ZteFnkgc6SNG8Ib2V0y30C3NEWin-8UPC0&usqp=CAU',
      },
      {
        id        : 3,
        name      : 'Noah',
        age       : 24,
        skill     : 'Golan',
        income    : 3000,
        location  : 'Rajshahi',
        gender    : 'male',
        photo     : 'https://conandaily.files.wordpress.com/2020/03/omar-borkan-al-gala.jpg',
      },
      {
        id        : 4,
        name      : 'Oliver',
        age       : 26,
        skill     : 'JavaScript',
        income    : 4000,
        location  : 'Rangpur',
        gender    : 'male',
        photo     : 'https://st2.depositphotos.com/1809585/5248/i/950/depositphotos_52487133-stock-photo-portrait-of-a-handsome-arab.jpg',
      },
      {
        id        : 5,
        name      : 'William',
        age       : 30,
        skill     : 'mern',
        income    : 5000,
        location  : 'Dinajpur',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTDNMbPM5RdHwQFssqVeDcwrilKxx0C9GYrg&usqp=CAU',
      },
      {
        id        : 6,
        name      : 'Elijah',
        age       : 33,
        skill     : 'Wordpress',
        income    : 6000,
        location  : 'Gazipur',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqAF5LwSX3h4rbyo1dD9gjc_BRnF3rCdA7DA&usqp=CAU',
      },
     
      {
        id        : 7,
        name      : 'Benjamin',
        age       : 18,
        skill     : 'Laravel',
        income    : 1000,
        location  : 'Dhaka',
        gender    : 'male',
        photo     : 'https://t4.ftcdn.net/jpg/02/45/56/35/360_F_245563558_XH9Pe5LJI2kr7VQuzQKAjAbz9PAyejG1.jpg',
      },
      {
        id        : 8,
        name      : 'Lucas',
        age       :  20,
        skill     : 'Django',
        income    : 2000,
        location  : 'Chittagong',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTN4QBL-gvv0o8pALvkaW5xSRe0BPe8CNobrQ&usqp=CAU',
      },
      {
        id        : 9,
        name      : 'Mason',
        age       : 24,
        skill     : 'Golan',
        income    : 3000,
        location  : 'Rajshahi',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZkBxRoOZDEwahHBXWTn2U1KOtDdNdQKTTF0q-FW6ff7heliuF1YQHYWDiydr5n1pFpcA&usqp=CAU',
      },
      {
        id        : 10,
        name      : 'Ethan',
        age       : 26,
        skill     : 'JavaScript',
        income    : 4000,
        location  : 'Rangpur',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm4dsk94vHtAYxRD3b3eRJB5E6f5zpcEKEqmdhNSMIVK8IVqhPWe5anEqINBCcGkLS9nE&usqp=CAU',
      },
      {
        id        : 11,
        name      : 'Alexander',
        age       : 30,
        skill     : 'mern',
        income    : 5000,
        location  : 'Dinajpur',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSy3T7SsXtpypnlgebh0RwcY4kIGo-z3Zniify3SCGVdSbplZqPvqmOqCQNKtQotpaFuKg&usqp=CAU',
      },
      {
        id        : 12,
        name      : 'Henry',
        age       : 33,
        skill     : 'Wordpress',
        income    : 6000,
        location  : 'Gazipur',
        gender    : 'male',
        photo     : 'https://www.maxpixel.net/static/photo/640/Person-Male-Face-Portrait-Human-Teenage-Man-Boy-6040022.jpg',
      },
     
      {
        id        : 13,
        name      : 'Jacob',
        age       : 18,
        skill     : 'Laravel',
        income    : 1000,
        location  : 'Dhaka',
        gender    : 'male',
        photo     : 'https://thumbs.dreamstime.com/z/calm-attractive-bearded-person-coat-over-green-pullover-normal-expression-standing-against-gray-background-man-stands-109588600.jpg',
      },
      {
        id        : 14,
        name      : 'Michael',
        age       :  20,
        skill     : 'Django',
        income    : 2000,
        location  : 'Chittagong',
        gender    : 'male',
        photo     : 'https://previews.123rf.com/images/sevendeman/sevendeman1909/sevendeman190900066/131062574-normal-straight-face-portrait-of-asian-man-in-blue-t-shirt-on-grey-background-.jpg',
      },
      {
        id        : 15,
        name      : 'Daniel',
        age       : 24,
        skill     : 'Golan',
        income    : 3000,
        location  : 'Rajshahi',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNA2mm3SjlORBPQU5KHBK4Gz0Q154ZjPO-RJOJHcr3BJxA9Db4hZ5PyzzyldGyhjRAXoU&usqp=CAU',
      },
      {
        id        : 16,
        name      : 'Logan',
        age       : 26,
        skill     : 'JavaScript',
        income    : 4000,
        location  : 'Rangpur',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQaaZ9BiaPb7DdMe5xt-01iHrBewJyKmRLMOQ&usqp=CAU',
      },
      {
        id        : 17,
        name      : 'Jackson',
        age       : 30,
        skill     : 'mern',
        income    : 5000,
        location  : 'Dinajpur',
        gender    : 'male',
        photo     : 'https://us.123rf.com/450wm/luismolinero/luismolinero1909/luismolinero190917934/130592146-handsome-young-man-in-pink-shirt-over-isolated-blue-background-keeping-the-arms-crossed-in-frontal-p.jpg?ver=6',
      },
      {
        id        : 18,
        name      : 'Sebastian',
        age       : 33,
        skill     : 'Wordpress',
        income    : 6000,
        location  : 'Gazipur',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRNCDplD_v_1KfSNO0zhO-6nSru6ntFmQkNBH7HAFqi_LJbwX2ejLIBOKx7_3Ju97AU_s&usqp=CAU',
      },
     
      {
        id        : 19,
        name      : 'Jack',
        age       : 18,
        skill     : 'Laravel',
        income    : 1000,
        location  : 'Dhaka',
        gender    : 'male',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAflTQb_pzefioXL_7RLkxTIqYQoX5I0IF4RWvmcz4RNqh0MEiN7LMYjDr5Ny0I-OgHmI&usqp=CAU',
      },
      {
        id        : 20,
        name      : 'Aiden',
        age       :  20,
        skill     : 'Django',
        income    : 2000,
        location  : 'Chittagong',
        gender    : 'male',
        photo     : 'https://ak.picdn.net/shutterstock/videos/2417927/thumb/1.jpg',
      },
      {
        id        : 21,
        name      : 'Mary',
        age       : 24,
        skill     : 'Golan',
        income    : 3000,
        location  : 'Rajshahi',
        gender    : 'female',
        photo     : 'https://www.mantruckandbus.com/fileadmin/media/bilder/02_19/219_05_busbusiness_interviewHeader_1485x1254.jpg',
      },
      {
        id        : 22,
        name      : 'Patricia',
        age       : 26,
        skill     : 'JavaScript',
        income    : 4000,
        location  : 'Rangpur',
        gender    : 'female',
        photo     : 'https://cdn.xxl.thumbs.canstockphoto.com/portrait-of-young-man-smiling-background-stock-photography_csp12568100.jpg',
      },
      {
        id        : 23,
        name      : 'Jennifer',
        age       : 30,
        skill     : 'mern',
        income    : 5000,
        location  : 'Dinajpur',
        gender    : 'female',
        photo     : 'https://media.istockphoto.com/photos/portrait-of-handsome-smiling-young-man-with-crossed-arms-picture-id1200677760?k=20&m=1200677760&s=612x612&w=0&h=JCqytPoHb6bQqU9bq6gsWT2EX1G5chlW5aNK81Kh4Lg=',
      },
      {
        id        : 23,
        name      : 'Linda',
        age       : 33,
        skill     : 'Wordpress',
        income    : 6000,
        location  : 'Gazipur',
        gender    : 'female',
        photo     : 'https://image.freepik.com/free-photo/handsome-young-man-white-t-shirt-cross-arms-chest-smiling-pleased_176420-21607.jpg',
      },
     
      {
        id        : 24,
        name      : 'Elizabeth',
        age       : 18,
        skill     : 'Laravel',
        income    : 1000,
        location  : 'Dhaka',
        gender    : 'female',
        photo     : 'https://thumbs.dreamstime.com/b/smiling-handsome-bearded-man-white-background-close-up-portrait-shirt-looking-camera-isolated-166160164.jpg',
      },
      {
        id        : 25,
        name      : 'Barbara',
        age       :  20,
        skill     : 'Django',
        income    : 2000,
        location  : 'Chittagong',
        gender    : 'female',
        photo     : 'https://i.pinimg.com/originals/c0/c0/e3/c0c0e3cada6195b8a0adfa0e2a38aaab.jpg',
      },
      {
        id        : 26,
        name      : 'Susan',
        age       : 24,
        skill     : 'Golan',
        income    : 3000,
        location  : 'Rajshahi',
        gender    : 'female',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYU1Nt3eEZdu9LTYUHYRMI4A0fR6gEwrtqEHmLZkPa2eO3WObqUgtyaCwbHpLDdu0wA4U&usqp=CAU',
      },
      {
        id        : 27,
        name      : 'Jessica',
        age       : 26,
        skill     : 'JavaScript',
        income    : 4000,
        location  : 'Rangpur',
        gender    : 'female',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdZygFL992LuaxJlp6tpZLOMi01DZnFMrkzEiY4FlceaKhorAbYVjHJXqoNsrQFJsfhGA&usqp=CAU',
      },
      {
        id        : 28,
        name      : 'Sarah',
        age       : 30,
        skill     : 'mern',
        income    : 5000,
        location  : 'Dinajpur',
        gender    : 'female',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShI9MBWam1PjNpUkOE_GR3L8lxYyXJ-L4oZVK-kMvJc_a5fsczKaBO4AMMMyDWPGVORK8&usqp=CAU',
      },
      {
        id        : 29,
        name      : 'Karen',
        age       : 33,
        skill     : 'Wordpress',
        income    : 6000,
        location  : 'Gazipur',
        gender    : 'female',
        photo     : 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR6mNeolQnmtuuUJ3SwppHCm0CfRXTBECfOw&usqp=CAU',
      },
     
   
]